### index
GET http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NDc5NzM2NjB9.jVRqDkWTcLamNfC3_to_cM5xw2wU-INw_WviHA44O8s

### show
GET http://localhost:3000/products/8.json


### create
POST http://localhost:3000/products.json
content-type: application/json

{
  "name": "Computer",
  "price": "3500",
  "image_url": "https://media.wired.com/photos/5fb2cc575c9914713ead03de/2:3/w_1200,h_1800,c_limit/Gear-Apple-MacBook-Air-top-down-SOURCE-Apple.jpg",
  "description": "Shiny new tech, you know you want to buy it!",
  "supplier_id": 2
}

### update
PATCH http://localhost:3000/products/10.json
content-type: application/json

{
  "name": "Disco Ball",
  "price": 350,
  "image_url": "https://ak.picdn.net/shutterstock/videos/1335892/thumb/1.jpg",
  "description": "Perfect for when you're feeling groovy!"
}

### destroy
DELETE http://localhost:3000/products/6


### user create (sign up)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Pippin",
  "email": "pippin@theonering",
  "password": "password",
  "password_confirmation": "password"
}


### sessions create (log in)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "pippin@theonering",
  "password": "password"
}

### order create
POST http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NDgwNTU3MzN9.JcheETaUr4gRT_vdGR7vmG2uuEBAEfBva3PGENOWy-A
Content-Type: application/json

{
  "product_id": "2",
  "quantity": 5
}

### orders show
GET http://localhost:3000/orders/1.json

### orders index
GET http://localhost:3000/orders.json
