### index
GET http://localhost:3000/products.json

### show
GET http://localhost:3000/products/11.json


### create
POST http://localhost:3000/products.json
content-type: application/json

{
  "name": "shoes",
  "price": "300",
  "image_url": "https://www.expensive-world.com/wp-content/uploads/2020/07/expensive-shoes.jpg",
  "description": "These gold-plated shoes will have you walking on air!"
}

### update
PATCH http://localhost:3000/products/5.json
content-type: application/json

{
  "name": "Hat",
  "price": 13,
  "image_url": "https://www.ikea.com/us/en/images/products/knorva-hat-blue__0812162_pe771942_s5.jpg",
  "description": "Love IKEA and bucket hats? This is the hat for you!"
}

### destroy
DELETE http://localhost:3000/products/6
