### index
GET http://localhost:3000/products.json

### show
GET http://localhost:3000/products/11.json


### create
POST http://localhost:3000/products.json
content-type: application/json

{
  "name": "shoes",
  "price": "300",
  "image_url": "https://www.expensive-world.com/wp-content/uploads/2020/07/expensive-shoes.jpg",
  "description": "These gold-plated shoes will have you walking on air!"
}

### update
PATCH http://localhost:3000/products/10.json
content-type: application/json

{
  "name": "Disco Ball",
  "price": 350,
  "image_url": "https://ak.picdn.net/shutterstock/videos/1335892/thumb/1.jpg",
  "description": "Perfect for when you're feeling groovy!"
}

### destroy
DELETE http://localhost:3000/products/6
